version: '3.8'

services:
  web:
    image: nginx:latest
    ports:
      - "8080:80" # expose container port 80 on host port 8080
    depends_on:
      - db
    restart: unless-stopped

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: examplePassword
      MYSQL_DATABASE: example_db
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3306:3306"
    restart: unless-stopped

volumes:
  db_data:
    driver: local
