name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  checkout:
    name: Checkout Repository
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
  lint:
    name: Lint YAML (Super-Linter)
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Lint YAML with Super-Linter
        uses: github/super-linter@v4
        env:
          VALIDATE_YAML: true
          # Ensure linter scans the workspace
          DEFAULT_WORKSPACE: ${{ github.workspace }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  validate-docker-compose:
    name: Validate Docker Compose
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Validate docker-compose.yml (if present)
        shell: bash
        run: |
          if [ -f "docker-compose.yml" ]; then
            echo "Found docker-compose.yml — validating..."
            docker compose -f docker-compose.yml config -q
            echo "docker-compose.yml is valid"
          else
            echo "docker-compose.yml not found — skipping"
          fi

  k8s-dry-run:
    name: Kubernetes dry-run (manifests)
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Kubernetes dry-run for k8s manifests (if present)
        shell: bash
        run: |
          if [ -d "k8s" ]; then
            echo "Found k8s/ directory — running kubectl dry-run checks..."

            # If kubeconfig/context is available, prefer server-side dry-run
            if kubectl version --client >/dev/null 2>&1; then
              if kubectl config view >/dev/null 2>&1 && kubectl config current-context >/dev/null 2>&1; then
                echo "kubeconfig/context found — attempting server-side dry-run..."
                if kubectl apply --dry-run=server -f k8s/; then
                  echo "server-side dry-run succeeded"
                else
                  echo "server-side dry-run failed — falling back to client dry-run (no validation)"
                  kubectl apply --dry-run=client --validate=false -f k8s/ || true
                fi
              else
                echo "No kubeconfig/context — running client dry-run with validation disabled"
                kubectl apply --dry-run=client --validate=false -f k8s/ || true
              fi
            else
              echo "kubectl not available — skipping k8s validation"
            fi

            echo "kubectl dry-run checks completed (non-fatal)"
          else
            echo "k8s/ directory not found — skipping"
          fi

  build:
    name: Build Application
    runs-on: ubuntu-latest
    needs: [validate-docker-compose, k8s-dry-run]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build
        run: echo "Build successful"

  notify:
    name: Notify
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Notify
        run: echo "Workflow finished"
